---
title: "Introduction to flexdashboard"
date: "`r Sys.Date()`"
author: "Jumping Rivers"
output:
  html_document:
  self_contained: yes
#    toc: true    
---
<!--
%\VignetteEngine{knitr::rmarkdown}
%\VignetteIndexEntry{Introduction to flexdashboard}
-->
  
## Overview

You can use flexdashboard to publish groups of related data visualizations as a dashboard. 
Install the package in the usual way
```{r eval=FALSE}
install.packages("flexdashboard")
```

## Layouts
  
  * Single column (fill) [HTML](flex_single_column_fill.html), [R](flex_single_column_fill.R), [Rmd](flex_single_column_fill.Rmd)
  * Single column (scroll) [HTML](flex_single_column_scroll.html), [R](flex_single_column_scroll.R), [Rmd](flex_single_column_scroll.Rmd)
  * Rows: [HTML](flex_row_orientation.html), [R](flex_row_orientation.R), [Rmd](flex_row_orientation.Rmd)
  * Multiple columns: [HTML](flex_multiple_columns.html), [R](flex_multiple_columns.R), [Rmd](flex_multiple_columns.Rmd)
  * Pages: [HTML](flex_pages.html), [R](flex_pages.R), [Rmd](flex_pages.Rmd)
  * Tabs: [HTML](flex_tabset_column.html), [R](flex_tabset_column.R), [Rmd](flex_tabset_column.Rmd)
  * Storyboards: [HTML](flex_storyboard.html), [R](flex_storyboard.R), [Rmd](flex_storyboard.Rmd)









